name: Composer security checks.

on:
  workflow_call:
    inputs:
      directory:
        description: 'The directory in which to run commands'
        type: string
        default: './'
      container:
        description: 'The docker image to use'
        type: string
        required: true
      source_key:
        description: 'The source cache key suffix'
        type: string
        default: 'composer'

defaults:
  run:
    shell: bash

jobs:
  phpcs:
    name: 'Composer security'
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Restore build from a previous step.
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          # We are only interested in a direct hit.
          key: build-${{ github.sha }}-${{ inputs.source_key }}

      - name: Abort if we have a source build cache miss.
        run: exit 1
        if: steps.restore-build.outputs.cache-hit != 'true'

      - name: Run security checks.
        run: |
          composer update --dry-run roave/security-advisories
