name: Install

on:
  workflow_call:
    inputs:
      container:
        description: 'The docker image to use'
        type: string
        required: true
      source_key:
        description: 'The source cache key suffix'
        type: string
        default: 'composer'
      copy_ci_settings:
        description: 'Optionally copy the settings.ci.php to settings.local.php. Also disables the db url for install.'
        type: boolean
        default: false
      sql_target_key:
        description: 'The target key for a SQL dump'
        type: string
        default: ''

defaults:
  run:
    shell: bash

jobs:
  phpcs:
    name: 'Site install'
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    services:
      db:
        image: mariadb:10.3
        ports: [3306]
        env:
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - name: Disable git safe directories as we are in a container.
        run: git config --global --add safe.directory '*'

      - name: Restore build from a previous step.
        uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: ./*
          # We are only interested in a direct hit.
          key: build-${{ github.sha }}-${{ inputs.source_key }}

      - name: Abort if we have a source build cache miss.
        run: exit 1
        if: steps.restore-build.outputs.cache-hit != 'true'

      - name: Copy CI settings.
        if: inputs.copy_ci_settings
        run: cp ./docroot/sites/default/settings.ci.php ./docroot/sites/default/settings.local.php

      - name: Run an install from existing config.
        run: ./vendor/bin/drush site:install --existing-config ${{ !inputs.copy_ci_settings && '--db-url=mysql://db:db@db:3306/db' || '' }}

      - name: Create a SQL dump.
        if: inputs.sql_target_key != ''
        run: ./vendor/bin/drush sql:dump --gzip --result-file "$(pwd)/db.sql"

      - name: Store the SQL dump.
        if: inputs.sql_target_key != ''
        uses: actions/cache/save@v3
        with:
          path: ./db.sql.gz
          enableCrossOsArchive: true
          key: build-${{ github.sha }}-${{ inputs.sql_target_key }}

      - name: Ensure config imported cleanly with no differences.
        run: |
          ./vendor/bin/drush cex -y
          git diff ./config
          git diff-index --quiet HEAD -- ./config
