name: Workflow to create a multi-dev on Pantheon.

on:
  workflow_call:
    inputs:
      pantheon_site_name:
        description: 'Pantheon site name.'
        type: string
        required: true
      strip_prefix:
        description: 'Optionally, a prefix to strip'
        type: string
        required: false
      safe_prefix:
        description: 'Optional single letter safe prefix'
        type: string
        required: false
        default: 't'
    secrets:
      PANTHEON_MACHINE_TOKEN:
        description: 'Machine token authorised to the Pantheon site.'
        required: true

defaults:
  run:
    shell: bash

jobs:
  create-multidev:
    name: 'Create a Pantheon multi-dev environment'
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref }}
      PANTHEON_SITE_NAME: ${{ inputs.pantheon_site_name }}
    steps:
      # It's safe to use a checkout here, instead of the cached build, just to
      # get access to the script.
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Create multi-dev-safe branch name.
        id: safe_branch
        uses: accessdigital/.github/.github/actions/pantheon-safe-branch@main
        with:
          branch_name: ${{ github.head_ref }}
          strip_prefix: ${{ inputs.strip_prefix }}
          safe_prefix: ${{ inputs.safe_prefix }}

      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'

      - name: Install Terminus.
        uses: pantheon-systems/terminus-github-actions@1.0.0
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Create or update a multidev environment.
        env:
          PANTHEON_SITE_URL: "pantheonsite.io"
        run: |
          terminus multidev:create \
            $PANTHEON_SITE_NAME.dev ${{ steps.safe_branch.outputs.branch_name }} \
            --no-files \
            --no-interaction
          echo "⚡ Multidev site created!" >> $GITHUB_STEP_SUMMARY
          echo "You can access it at: https://${{ steps.safe_branch.outputs.branch_name }}-$PANTHEON_SITE_NAME.$PANTHEON_SITE_URL" >> $GITHUB_STEP_SUMMARY
