name: PHP Coding Standards (deprecated)
# Deprecated in favour of php-analysis.yml.

on:
  workflow_call:
    inputs:
      directory:
        description: 'The directory to run in'
        type: string
        default: './'
      container:
        description: 'The docker image to use'
        type: string
        required: true
      source_key:
        description: 'The source cache key suffix'
        type: string
        default: 'composer'

defaults:
  run:
    shell: bash

jobs:
  phpcs:
    name: 'PHP Coding Standards (deprecated)'
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Restore build from a previous step.
        uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: ./*
          fail-on-cache-miss: true
          # We are only interested in a direct hit.
          key: build-${{ github.sha }}-${{ inputs.source_key }}

      - name: Run PHPCS.
        run: |
          cd ${{ inputs.directory }}
          ./vendor/bin/phpcs
